[tool.briefcase]
project_name = "Node-Z"
bundle = "com.nodez"
version = "1.0.0"
url = "https://www.getbtcz.com"
license = "MIT license"
author = "BTCZCommunity"
author_email = "dragkhai@gmail.com"

[tool.briefcase.app.nodez]
formal_name = "Node-Z"
description = "Full NodeZ"
long_description = """More details about the app should go here.
"""
icon = "nodez/resources/app_logo"
sources = [
    "nodez",
]
test_sources = [
    "tests",
]

requires = [
]
test_requires = [
    "pytest",
]

[tool.briefcase.app.nodez.windows]
requires = [
    "toga-winforms==0.4.4",
    "requests"
]

use_full_install_path = false

# Web deployments
[tool.briefcase.app.nodez.web]
requires = [
    "toga-web~=0.4.0",
]
style_framework = "Shoelace v2.3"

